"""empty message

Revision ID: a264381cc016
Revises: 1c20b38b5c29
Create Date: 2021-06-17 16:52:10.919637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a264381cc016'
down_revision = '1c20b38b5c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('home', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configurations_created_at'), 'configurations', ['created_at'], unique=False)
    op.create_index(op.f('ix_configurations_updated_at'), 'configurations', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configurations_updated_at'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_created_at'), table_name='configurations')
    op.drop_table('configurations')
    # ### end Alembic commands ###
