"""empty message

Revision ID: ce4ef3f5a5ae
Revises: 3901884ad39d
Create Date: 2021-06-18 14:24:33.729697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce4ef3f5a5ae'
down_revision = '3901884ad39d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('video', sa.String(), nullable=False),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('doc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_created_at'), 'videos', ['created_at'], unique=False)
    op.create_index(op.f('ix_videos_updated_at'), 'videos', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_updated_at'), table_name='videos')
    op.drop_index(op.f('ix_videos_created_at'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
